#!/bin/bash

#jpg_name=${1}
#dng_name=$(basename $jpg_name .JPG).DNG
#if ! [ -f $dng_name ]; then
	#echo "dng is not present for " $jpg_name
	#rm $jpg_name
	#rm $jpg_name.xmp
#fi

xmp_name=${1}
jpg_name=$(basename $xmp_name .xmp)
if ! [ -f $jpg_name ]; then
	echo "jpg is not present for " $xmp_name
	rm $xmp_name
fi
